version: "3"
services:
  profile:
    image: profileservice
    container_name: profile
    ports:
      - 8081:8080
    environment:
      - SERVER_PORT=8080
      - AUTH_URL=http://auth:8080
    depends_on:
      - auth
  auth:
    image: authservice
    container_name: auth
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
  gateway:
    image: gateway
    container_name: gateway
    depends_on:
      - profile
      - auth
    ports:
      - 8082:8080
    environment:
      - SERVER_PORT=8080
      - PROFILE_URL=http://profile:8080
      - AUTH_URL=http://auth:8080
